---
# Add 'root' label to any root file changes
# Quotation marks are required for the leading asterisk
go:
  - changed-files:
      - any-glob-to-any-file: "cmd/**.go"
      - any-glob-to-any-file: "pkg/**.go"
      - any-glob-to-any-file: "collector/**.go"
      - any-glob-to-any-file: "config/**.go"
      - any-glob-to-any-file: "exporter/**.go"

dependencies:
  - changed-files:
      - any-glob-to-any-file: "go.mod"
      - any-glob-to-any-file: "go.sum"
      - any-glob-to-any-file: mise.toml

# Add 'Documentation' label to any changes within 'docs' folder or any subfolders
documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**
      - any-glob-to-any-file: README.md

ci:
  - changed-files:
      - any-glob-to-any-file: .github/**
      - any-glob-to-any-file: Makefile

repo:
  - changed-files:
      - any-glob-to-any-file: .codecov.yml
      - any-glob-to-any-file: .chglog.yml
      - any-glob-to-any-file: .golangci.yml
      - any-glob-to-any-file: .goreleaser.yaml
      - any-glob-to-any-file: .markdownlint.yaml
      - any-glob-to-any-file: .prettierrc.yaml
      - any-glob-to-any-file: .yamlfmt.yml
      - any-glob-to-any-file: .yamllint.yml
      - any-glob-to-any-file: changelog.yaml
      - any-glob-to-any-file: scripts/**.sh

docker:
  - changed-files:
      - any-glob-to-any-file: Dockerfile
      - any-glob-to-any-file: docker-bake.hcl

# Add label to any PR where the head branch name starts with label name or has a label name in the section in the name
feature:
  - head-branch: ["^feature", "feature"]
fix:
  - head-branch: ["^fix", "fix"]
chore:
  - head-branch: ["^chore", "chore"]
docs:
  - head-branch: ["^docs", "docs"]
security:
  - head-branch: ["^security", "security"]
