# yamlfmt configuration for project
formatter:
  type: basic
  indent: 2
  include_document_start: true
  line_ending: lf
  retain_line_breaks: true
  max_line_length: 120
  scan_folded_as_literal: false
  indentless_arrays: false
  drop_merge_tag: false
  pad_line_comments: 2
  trim_trailing_whitespace: true
  # Don't force array/map style - preserve existing flow/block formatting
  # This allows compact inline syntax like {name: foo, key: bar} and [ALL]
  retain_line_breaks_single: true
